export const MESSAGES = {
  en: {
    appTitle: "MarketFit", language: "Language", temporary: "Your PDF resume and captured job stay in this panel unless you explicitly run AI analysis.",
    profile: "Your profile", resumePdf: "CV PDF", choosePdf: "Choose a text-based PDF", noResume: "No resume PDF selected.", uploadHint: "1. Upload a text-based PDF resume. 2. Open a full job posting tab, choose an AI provider, then run AI analysis.", market: "Target market", workAuthorization: "Work authorization", clearSession: "Clear local session",
    authorized: "Already authorized", needsSponsorship: "Needs sponsorship", openWorkPermit: "Open work permit", studentGraduate: "Student or graduate route", temporaryRoute: "Other temporary route", unknown: "Unknown",
    currentJob: "Current job", refreshJob: "Re-read job page", editJob: "Edit job text", close: "Close", jobTitle: "Job title", company: "Company", jobLocation: "Location", jobDescriptionText: "Job description", saveJobText: "Use this JD",
    noData: "Upload a CV PDF, choose an AI provider, then run AI analysis while the full job posting is open.", missingResume: "Upload a CV PDF before analysing a job.", capturing: "Reading the current job page", captureBlocked: "This page cannot be read yet.", noJobContent: "No usable job description was found on this page.", grantSiteAccess: "Allow reading this site", accessDenied: "Site access was not granted. You can allow it and try again.", captured: "Captured {host} for AI analysis.", lowConfidence: "The page was captured, but job details are incomplete. Open the full job posting and try again.", lowQualityJob: "The captured job text is too short or incomplete ({chars} characters). Re-read the page or edit/paste the JD.", jobQualityLine: "{chars} chars · {method} · {confidence}% confidence", capturedJobStats: "Job ready for AI: {chars} characters, {confidence}% confidence.", jobReadyForAi: "Job page is ready. Choose an AI provider and run analysis.",
    pdfReading: "Reading your PDF locally", pdfReady: "{name} ready: {pages} page(s).", pdfTruncated: "{name} is ready; only the first 60,000 characters are used.", pdfFailed: "The PDF could not be used.",
    confidence: "Confidence", whatMissing: "What is missing", blockers: "Confirmed blockers", verifyFirst: "Verify first", strongestMatches: "Strongest evidence matches", highestGaps: "Highest-impact gaps", nextAction: "Recommended next action", allFindings: "All findings and evidence", limitation: "Important limitation", authorizationChecks: "Separate authorization checks",
    employerSponsorship: "Employer sponsorship eligibility", roleSponsorship: "Role-level sponsorship willingness", candidateEligibility: "Candidate visa eligibility",
    agentHeading: "AI job analysis", agentExplain: "AI reads the full PDF-derived CV and the current job page, then returns cited role understanding, evidence, gaps, risks, and preparation guidance.", bridgeUnpaired: "Local AI Bridge is not paired.", bridgePort: "Bridge port", pairingCode: "One-time pairing code", pairBridge: "Pair bridge", refreshStatus: "Refresh status", disconnect: "Disconnect", bridgeConnection: "Local AI Bridge connection", cliBridgeHelp: "Codex CLI and Claude Code use the existing local login, so pair the Local AI Bridge below.", apiDirectHelp: "The session key remains only in this open panel. MarketFit asks before directly connecting to this provider, does not use a local Bridge, and never saves the key.", chooseProvider: "Choose a provider", provider: "AI provider", codex: "Codex CLI", claudeCode: "Claude Code", openaiApi: "OpenAI API key", anthropicApi: "Anthropic API key", sessionApiKey: "Session API key", apiModel: "Model", openAiGpt5Mini: "GPT-5 mini (faster, lower cost)", openAiGpt5: "GPT-5 (more capable)", anthropicSonnet: "Claude Sonnet 4.6 (balanced)", anthropicOpus: "Claude Opus 4.6 (most capable)", runAiReview: "Analyze current job with AI", agentPrivacy: "CLI providers send the current PDF-derived CV text and job page through the paired local Bridge. API-key providers connect directly to their selected provider only after you run an analysis. API keys remain only in the open panel and are never saved.",
    privacy: "Privacy and permissions", privacyExplain: "Default PDF parsing and page capture stay local. AI transfer occurs only after you explicitly run it.", previewPayload: "Preview optional AI payload", extensionPermission: "CLI providers use the paired local Bridge. API-key providers request direct access only to their selected API domain when you run an analysis.",
    paired: "Paired to 127.0.0.1:{port}. Available: {providers}.", bridgeUnavailable: "Saved pairing at 127.0.0.1:{port} is unavailable. Start or re-pair the Bridge.", bridgePaired: "Local AI Bridge paired.", pairingFailed: "Bridge pairing failed.", bridgeDisconnected: "Local Bridge disconnected. Restart it before pairing again.", chooseProviderFirst: "Choose an AI provider first.", aiFinished: "AI analysis completed with {provider}.", requestingAi: "Job captured. Requesting AI analysis", apiKeyNeeded: "Enter a session API key for the selected provider.", directAccessDenied: "Direct access to the selected AI provider was not allowed.",
    localAnalysisMethod: "Local evidence analysis", localAnalysisExplain: "Uses explicit job requirements, safe skill aliases such as k8s/Kubernetes and RAG/retrieval-augmented generation, and evidence strength in the CV. It does not infer unstated equivalence; run AI review for full CV/JD interpretation.", aiReview: "AI analysis", aiSupplement: "AI-generated analysis. Every displayed conclusion is accompanied by CV or job-page source evidence; verify anything material before acting.", jobUnderstanding: "Job understanding", candidatePositioning: "Candidate positioning", fitNarrative: "Evidence-based fit narrative", evidenceRequirements: "Evidence-backed requirements", aiStrengths: "Evidence-backed strengths", aiGaps: "Evidence gaps", aiRisks: "Role-fit risks to verify", resumeTailoring: "Resume tailoring", interviewFocus: "Interview focus", employerQuestions: "Questions and uncertainties", suggestedActions: "Suggested next steps",
    apply: "Apply", tailorThenApply: "Tailor then apply", stretch: "Stretch", verifyFirstDecision: "Verify first", doNotPrioritize: "Do not prioritize", needsConfirmation: "Needs confirmation", insufficient: "More evidence needed"
  },
  zh: {
    appTitle: "MarketFit", language: "界面语言", temporary: "PDF 简历和当前职位默认只保留在此侧栏中；仅在你主动运行 AI 分析时才会进行额外传输。",
    profile: "你的资料", resumePdf: "PDF 简历", choosePdf: "选择可提取文字的 PDF", noResume: "尚未选择 PDF 简历。", uploadHint: "1. 上传可提取文字的 PDF 简历。2. 打开完整职位详情页、选择 AI 提供商后，运行 AI 分析。", market: "目标市场", workAuthorization: "工作授权", clearSession: "清除本地会话",
    authorized: "已具备工作授权", needsSponsorship: "需要雇主担保", openWorkPermit: "开放工作许可", studentGraduate: "学生或毕业生路径", temporaryRoute: "其他临时路径", unknown: "未知",
    currentJob: "当前职位", refreshJob: "重新读取职位页", editJob: "编辑职位文本", close: "关闭", jobTitle: "职位名称", company: "公司", jobLocation: "地点", jobDescriptionText: "职位描述", saveJobText: "使用这份 JD",
    noData: "上传 PDF 简历、选择 AI 提供商后，在打开完整职位详情页时运行 AI 分析。", missingResume: "请先上传 PDF 简历，再分析职位。", capturing: "正在读取当前职位页面", captureBlocked: "暂时无法读取此页面。", noJobContent: "未在此页面找到可用的职位描述。", grantSiteAccess: "允许读取此网站", accessDenied: "未获得网站读取权限。允许后可再次尝试。", captured: "已抓取 {host}，准备进行 AI 分析。", lowConfidence: "职位页面已抓取，但关键信息不完整。请打开完整职位详情后重试。", lowQualityJob: "读取到的职位文本过短或不完整（{chars} 个字符）。请重新读取页面，或编辑/粘贴 JD。", jobQualityLine: "{chars} 字符 · {method} · {confidence}% 置信度", capturedJobStats: "职位已可用于 AI：{chars} 个字符，{confidence}% 置信度。", jobReadyForAi: "职位页面已就绪。请选择 AI 提供商并运行分析。",
    pdfReading: "正在本地读取 PDF", pdfReady: "{name} 已就绪：{pages} 页。", pdfTruncated: "{name} 已就绪；仅使用前 60,000 个字符。", pdfFailed: "无法使用该 PDF。",
    confidence: "置信度", whatMissing: "缺少的信息", blockers: "已确认的阻塞项", verifyFirst: "优先核实", strongestMatches: "最强证据匹配", highestGaps: "影响最大的差距", nextAction: "建议的下一步", allFindings: "全部发现与证据", limitation: "重要限制", authorizationChecks: "工作授权的独立核查",
    employerSponsorship: "雇主担保资格", roleSponsorship: "该职位的担保意愿", candidateEligibility: "候选人的签证资格",
    agentHeading: "AI 职位分析", agentExplain: "AI 会阅读完整的 PDF 简历文本和当前职位页面，给出带原文引证的岗位理解、匹配证据、缺口、风险和准备建议。", bridgeUnpaired: "本地 AI Bridge 尚未配对。", bridgePort: "Bridge 端口", pairingCode: "一次性配对码", pairBridge: "配对 Bridge", refreshStatus: "刷新状态", disconnect: "断开连接", bridgeConnection: "本地 AI Bridge 连接", cliBridgeHelp: "Codex CLI 和 Claude Code 使用本机已有登录态，请在下方配对本地 AI Bridge。", apiDirectHelp: "会话 API Key 只保留在当前打开的侧栏中。MarketFit 会在直连该提供商前请求权限，不使用本地 Bridge，也不会保存 Key。", chooseProvider: "选择提供商", provider: "AI 提供商", codex: "Codex CLI", claudeCode: "Claude Code", openaiApi: "OpenAI API Key", anthropicApi: "Anthropic API Key", sessionApiKey: "会话 API Key", apiModel: "模型", openAiGpt5Mini: "GPT-5 mini（更快、成本更低）", openAiGpt5: "GPT-5（能力更强）", anthropicSonnet: "Claude Sonnet 4.6（均衡）", anthropicOpus: "Claude Opus 4.6（能力最强）", runAiReview: "用 AI 分析当前职位", agentPrivacy: "Codex CLI 和 Claude Code 会通过已配对的本地 Bridge 发送当前 PDF 简历文字和职位页面。选择 API Key 后，仅在你运行分析时才会直连对应提供商。API Key 只保留在当前打开的侧栏中，不会被保存。",
    privacy: "隐私与权限", privacyExplain: "默认的 PDF 解析和页面抓取都在本地完成。仅在你主动运行 AI 分析时才会发生数据传输。", previewPayload: "预览可选 AI 负载", extensionPermission: "Codex CLI 和 Claude Code 使用已配对的本地 Bridge；API Key 提供商仅在你运行分析时请求直连所选 API 域名。",
    paired: "已配对至 127.0.0.1:{port}。可用：{providers}。", bridgeUnavailable: "已保存的 127.0.0.1:{port} 配对不可用。请启动或重新配对 Bridge。", bridgePaired: "本地 AI Bridge 已配对。", pairingFailed: "Bridge 配对失败。", bridgeDisconnected: "本地 Bridge 已断开。再次配对前请重启它。", chooseProviderFirst: "请先选择 AI 提供商。", aiFinished: "已使用 {provider} 完成 AI 分析。", requestingAi: "职位已读取，正在请求 AI 分析", apiKeyNeeded: "请为选定提供商填写会话 API Key。", directAccessDenied: "未允许直连所选 AI 提供商。",
    localAnalysisMethod: "本地证据分析", localAnalysisExplain: "使用职位中的明确要求、安全的技能别名（如 k8s/Kubernetes、RAG/检索增强生成）以及简历中的证据强度。它不会推断未写明的等价经验；需要完整解读 CV/JD 时请运行 AI 评估。", aiReview: "AI 分析结果", aiSupplement: "由 AI 生成。每一项展示结论都会附带简历或职位页面的原文证据；执行重要行动前请自行核实。", jobUnderstanding: "岗位理解", candidatePositioning: "候选人定位", fitNarrative: "基于证据的匹配叙述", evidenceRequirements: "带证据的要求", aiStrengths: "有证据的优势", aiGaps: "证据缺口", aiRisks: "需要核实的岗位匹配风险", resumeTailoring: "简历针对性优化", interviewFocus: "面试准备重点", employerQuestions: "疑问与待核实项", suggestedActions: "建议的下一步",
    apply: "建议投递", tailorThenApply: "优化后投递", stretch: "挑战性职位", verifyFirstDecision: "先核实", doNotPrioritize: "不建议优先投递", needsConfirmation: "需要确认", insufficient: "资料不足"
  }
};

export function t(locale, key) {
  return MESSAGES[locale]?.[key] || MESSAGES.en[key] || key;
}

export function format(locale, key, values = {}) {
  return t(locale, key).replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ""));
}

export function applyTranslations(root, locale) {
  root.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(locale, element.dataset.i18n); });
  root.querySelectorAll("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(locale, element.dataset.i18nPlaceholder); });
}

export function priorityLabel(locale, priority) {
  const map = { apply: "apply", tailor_then_apply: "tailorThenApply", stretch: "stretch", verify_first: "verifyFirstDecision", do_not_prioritize: "doNotPrioritize", needs_confirmation: "needsConfirmation", insufficient: "insufficient" };
  return t(locale, map[priority] || priority);
}
